 DATA6 = {
    :player_keys =>
    ["name", "position", "nfl_team", "projected_points", "team_id"],
    :players => [
      ["Patrick Mahomes", "QB", "KC", 578, 1],
      ["Drew Brees", "QB", "NO", 475, 2],
      ["Tom Brady", "QB", "TB", 472, 3],
      ["Lamar Jackson", "QB", "BAL", 587, 4],
      ["Russell Wilson", "QB", "SEA", 518, 5],
      ["Kyler Murray", "QB", "ARI", 505, 6],
      ["Aaron Rodgers", "QB", "GB", 471, 7],
      ["Cam Newton", "QB", "NE", 454, 8],
      ["Matt Ryan", "QB", "ATL", 462, 9],
      ["Ryan Tannehill", "QB", "TEN", 395, 10],
      ["Josh Allen", "QB", "BUF", 486, 1],
      ["Dalvin Cook", "RB", "MIN", 393, 1],
      ["Nick Chubb", "RB", "CLE", 352, 2],
      ["Joe Mixon", "RB", "CIN", 376, 3],
      ["Derrick Henry", "RB", "TEN", 392, 4],
      ["Alvin Kamara", "RB", "NO", 374, 5],
      ["Aaron Jones", "RB", "GB", 342, 6],
      ["Clyde Edwards-Helaire", "RB", "KC", 370, 7],
      ["Ezekiel Elliott", "RB", "DAL", 412, 8],
      ["Austin Ekeler", "RB", "LAC", 313, 9],
      ["Kareem Hunt", "RB", "CLE", 228, 10],
      ["Chris Carson", "RB", "SEA", 323, 1],
      ["Frank Gore", "RB", "NYJ", 133, 2],
      ["Jonathan Taylor", "RB", "IND", 282, 3],
      ["Kenyan Drake", "RB", "ARI", 325, 4],
      ["James Robinson", "RB", "JAX", 77, 5],
      ["Zack Moss", "RB", "BUF", 158, 6],
      ["J.K. Dobbins", "RB", "BAL", 234, 7],
      ["Rex Burkhead", "RB", "NE", 100, 8],
      ["Antonio Gibson", "RB", "WAS", 170, 9],
      ["Christian McCaffrey", "RB", "CAR", 527, 10],
      ["Saquon Barkley", "RB", "NYG", 413, 1],
      ["Le'Veon Bell", "RB", "NYJ", 306, 1],
      ["Leonard Fournette", "RB", "TB", 279, 1],
      ["Raheem Mostert", "RB", "SF", 301, 1],
      ["James Conner", "RB", "PIT", 305, 1],
      ["Tyreek Hill", "WR", "KC", 315, 1],
      ["Chris Godwin", "WR", "TB", 298, 2],
      ["Calvin Ridley", "WR", "ATL", 248, 3],
      ["Julio Jones", "WR", "ATL", 313, 4],
      ["Cooper Kupp", "WR", "LAR", 262, 5],
      ["DeAndre Hopkins", "WR", "ARI", 304, 6],
      ["DK Metcalf", "WR", "SEA", 244, 7],
      ["Keenan Allen", "WR", "LAC", 247, 8],
      ["Michael Thomas", "WR", "NO", 323, 9],
      ["Tyler Lockett", "WR", "SEA", 265, 10],
      ["Amari Cooper", "WR", "DAL", 274, 1],
      ["Kenny Golladay", "WR", "DET", 286, 2],
      ["Tyler Boyd", "WR", "CIN", 221, 3],
      ["Chase Claypool", "WR", "PIT", 67, 4],
      ["Justin Jefferson", "WR", "MIN", 142, 5],
      ["JuJu Smith-Schuster", "WR", "PIT", 249, 6],
      ["Stefon Diggs", "WR", "BUF", 222, 7],
      ["DeVante Parker", "WR", "MIA", 222, 8],
      ["Mike Evans", "WR", "TB", 312, 9],
      ["CeeDee Lamb", "WR", "DAL", 193, 10],
      ["Robert Woods", "WR", "LAR", 264, 1],
      ["Jarvis Landry", "WR", "CLE", 200, 1],
      ["Julian Edelman", "WR", "NE", 190, 1],
      ["Odell Beckham Jr.", "WR", "CLE", 259, 1],
      ["A.J. Brown", "WR", "TEN", 282, 1],
      ["Travis Kelce", "TE", "KC", 280, 1],
      ["Darren Waller", "TE", "LV", 205, 2],
      ["Evan Engram", "TE", "NYG", 176, 3],
      ["Hunter Henry", "TE", "LAC", 174, 4],
      ["Noah Fant", "TE", "DEN", 155, 5],
      ["Mike Gesicki", "TE", "MIA", 164, 6],
      ["Eric Ebron", "TE", "PIT", 153, 7],
      ["Zach Ertz", "TE", "PHI", 223, 8],
      ["Jimmy Graham", "TE", "CHI", 133, 9],
      ["George Kittle", "TE", "SF", 265, 10],
      ["Jason Sanders", "K", "MIA", 172, 1],
      ["Harrison Butker", "K", "KC", 200, 2],
      ["Younghoe Koo", "K", "ATL", 185, 3],
      ["Chris Boswell", "K", "PIT", 177, 4],
      ["Robbie Gould", "K", "SF", 202, 5],
      ["Rodrigo Blankenship", "K", "IND", 170, 6],
      ["Justin Tucker", "K", "BAL", 199, 7],
      ["Dan Bailey", "K", "MIN", 177, 8],
      ["Daniel Carlson", "K", "LV", 187, 9],
      ["Jason Myers", "K", "SEA", 182, 10]
      ]}
  
      def make_players
        DATA6[:players].each do |player|
          new_player = Player.new
          player.each_with_index do |attribute, i|
            new_player.send(DATA6[:player_keys][i] + "=", attribute)
          end
          new_player.save
        end
      end

      make_players